name: Graces-blog
favicon: null
layout_spectrum: 0.23688766919076443
typography_spectrum: 0.02804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5378451880533248
  lightness: 0.5390959570650011
  saturation: 0.9950853774789721
  rhythmicContrast: 0.28585475916042924
purpose: []
